# Generated by Django 4.1.4 on 2022-12-17 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neki', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prostorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_prostorije', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('kat', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('naziv_prostorije', models.TextField(default='Prazna dvorana')),
            ],
        ),
        migrations.CreateModel(
            name='Voditelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.CharField(max_length=100)),
                ('telefon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('vrijeme_pocetka', models.DateTimeField(verbose_name='Datum početka')),
                ('vrijeme_zavrsetka', models.DateTimeField(verbose_name='Datum planiranog završetka')),
                ('prostorija_izvodjenja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prostorija')),
                ('voditelji_aktivnosti', models.ManyToManyField(to='main.voditelj')),
            ],
        ),
    ]
