# Generated by Django 3.2.12 on 2022-12-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221217_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racunalo',
            old_name='broj_racunala',
            new_name='id_racunala',
        ),
    ]
