# Generated by Django 3.2.12 on 2022-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_broj_racunala_racunalo_id_racunala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditelj',
            name='telefon',
            field=models.CharField(max_length=15),
        ),
    ]
